### ISSUE TITLE
Access to the view instance

### ISSUE THREAD

**Issue by wlkns** [AminZoubaa/vue-async-router-demo#1]
Hi,

Would it be possible for me to access the Vue instance, I need properties registered on it e.g.

```js
{
    props: async () => {
        users: await this.$http.get('users')
    }
}
```

**Comment by AminZoubaa** [comment]
Hey @wlkns,

you can't access the instance directly in this scope.
Am i right that you are using the `'vue-resource'` package?

**There are several options, for example:**

### With `vue-resource/axios`
Make sure that u import the **http** service, wich is what u want to use, instead of accessing it via `this`.

```jsx
import { Http as $http } from 'vue-resource';
// OR
import axios as $http from 'axios';

export default new Router({
  routes: [
    ...,
    {
      path: '/page-a',
      name: 'page-a',
      component: ExampleComponent,
      props: async () => ({
        users: await $http.get('https://jsonplaceholder.typicode.com/users')
      }),
    },
  ],
});
```
### With `fetch`
If you want to use fetch maybe use something like this, that can fit for you.
MDN: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

```jsx
const $http = {
  fetch: async (method, url, data) => {
    const response = await fetch(url, {
      method, // *GET, POST, PUT, DELETE, etc.
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    return response.json();
  },
  get: (url, data) => $http.fetch('GET', url, data),
  post: (url, data) => $http.fetch('POST', url, data),
};

(async () => {
    const apiUrl = 'https://jsonplaceholder.typicode.com/users';
    const responseData = await $http.get(apiUrl);
    console.log(responseData);
})();
```

Considering the time that passed, I hope anyhow that i could helped you.
